### ISSUE TITLE
Transfer to purescript-contrib?

### ISSUE THREAD

**Issue by jamesdbrock** [AlexaDeWit/purescript-text-encoding#7]
Hi @AlexaDeWit , thanks for maintaining this package. Would you like to transfer it to https://github.com/orgs/purescript-contrib ? If you transferred it to purescript-contrib then we would also like you to join purescript-contrib as a maintainer, but if you don't want to maintain this package any more then I could be the maintainer.

**Comment by AlexaDeWit** [comment]
I'm happy for you to migrate it over if you like.

I've not been active in recent time within the purescript community, so I'm happy to have it taken over.

**Comment by jamesdbrock** [comment]
I've come to realize that https://pursuit.purescript.org/packages/purescript-web-encoding is the successor package to this package, so I guess we don't need to transfer this one. But thanks for your generosity, and thanks for maintaining this __text-encoding__ package. I used it many times, it worked like a charm.
